### ISSUE TITLE
Spread in object literals is not support in “lt iOS 11.3”

### ISSUE THREAD

**Issue by lizy0329** [kangax/compat-table#1785] opened 2022-01-21 04:09 UTC
In my case, "lt iOS 11.3" will throw error: "SyntaxError: Unexpected token '...'. Expected a property name." 😂😂😂

We also have a large number of IOS 11.1 11.2 machines in our company for testing

**Comment by ljharb** [comment] 2022-01-21 04:19
Our current data has it supported in Safari 11.1, which is marked as being equivalent to iOS 11.3 - iOS 11.1 and 11.2 is expected to lack this feature.

Are you saying that iOS 11.3 lacks this feature? Can you confirm the version of Mobile Safari being used?

**Comment by lizy0329** [comment] 2022-01-21 04:34
Yes. We use  IOS 11.1 11.2 iPhone machines in our company for testing, iOS 11.3 is support, but iOS 11.1 11.2 throw error

**Comment by evanw** [comment] 2022-01-21 04:36
I'm coming from https://github.com/evanw/esbuild/issues/1949 for context. It sounds like maybe there's confusion between the Safari version and the iOS version then.

> Safari 11.1, which is marked as being equivalent to iOS 11.3

Where is that marked? Is that part of the data provided by this repo?

**Comment by ljharb** [comment] 2022-01-21 04:47
@evanw yes, it's in the data provided by this repo; in environments.json. When two environments are equivalent - like node and chrome, or iOS and Safari - we equate them so that we don't have to duplicate all the results.

@lizy0329 iOS 11.1 and 11.2 do not support object spread/rest syntax, and aren't expected to.

**Comment by evanw** [comment] 2022-01-21 04:57
Sounds like it's working as intended then! Sorry about the confusion. That's my fault. I often check for the compatibility data by reading the JSON file on GitHub instead of running code because it's easy to link to it, but then I miss stuff like this.

**Closed** 2022-01-21 04:58 UTC

**Comment by lizy0329** [comment] 2022-01-21 05:29
But, how to explain this table?
![image](https://user-images.githubusercontent.com/9499272/150470449-274e3217-0ae1-45d1-9055-4c02f911908f.png)

This table sends us the message that iOS and safari version information are equal. So went @evanw check the env info:
![image](https://user-images.githubusercontent.com/9499272/150471056-e31f36c0-e197-4dd7-9f96-8d75bc3510d2.png)

He thinks safari11_1 is the same as iOS 11.1 and say “Spread in object literals is support in “iOS 11.1”

**Comment by evanw** [comment] 2022-01-21 05:34
Sorry, I was wrong. There's a mapping from Safari version to iOS version:

https://github.com/kangax/compat-table/blob/f156b2f5c2cb14e4d79cfaa04c3b746a5b781b32/environments.json#L4922-L4927

So iOS 11.3 maps to Safari 11.1, and it looks like this data set is consistent with the Can I use database after all (as far as I can tell).

**Comment by lizy0329** [comment] 2022-01-21 05:43
> Sorry, I was wrong. There's a mapping from Safari version to iOS version:
> 
> https://github.com/kangax/compat-table/blob/f156b2f5c2cb14e4d79cfaa04c3b746a5b781b32/environments.json#L4922-L4927
> 

We still believe in https://en.wikipedia.org/wiki/Safari_version_history#Safari_11_2 ？
![image](https://user-images.githubusercontent.com/9499272/150472350-7a965157-e73a-40e5-b522-1e2276f98090.png)

Safari is no 11.1 here 😂 so you can not to say: "maps to Safari 11.1"

**Comment by ljharb** [comment] 2022-01-21 05:50
@lizy0329 "spread syntax for iterable objects" isn't the syntax you're talking about. You need to look at "object rest/spread properties", which is a "no" for iOS 11, and a "yes" for iOS 11.3.

**Comment by lizy0329** [comment] 2022-01-21 05:58
@ljharb Thank you for your patience in explaining
